<html>
  <head>
  <script type="text/javascript">
    function updateTextInput(val) {
      document.getElementById('textInput').value=val; 
    }
  </script>
  </head>
  <body>
    <input type="range" name="rangeInput" min="0" max="100" onchange="updateTextInput(this.value);">                                                       
    <input type="text" id="textInput" value="">
  </body>
</html>

 <input type="button" value="New Window!" onClick="window.open('/var/www/html/quiz/public','theirdesktop','width=400,height=200')">
 <input type="button" value="New Window!" onClick="window.open('/var/www/html/quiz/public','theirdesktop','width=400,height=200')">

 <a href="/var/www/html/quiz/public">temp</a>