<?php
$title = 'FFMpeg and Mp3splt  Scan';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
// echo $this->serverUrl();
$mp3Files = $this->mp3Files;
$oggFiles = $this->oggFiles;
// foreach ($audioRes as $audioFile) {
echo "<div class='col-md-6'>";
	for($i=0; $i<count($mp3Files); $i++){
		echo "<div>";
echo 'No. '.($i+1);
// echo $mp3Files["$i"];
	echo $this->partial('partial/audio.phtml', array(
		// 'audioFile' => $audioFile)); 
		'mp3File' => $mp3Files[$i],
		'oggFile' => $oggFiles[$i]
		)); 
	echo "</div>";
}
	echo "</div>";
?>

<div class="col-md-6">
1111111
</div>
