<?php
$form->prepare();
echo $this->form()->openTag($form); 
?>
<tr>
	<td>
	<?php echo 'No.'.$this->i;?>
	</td>
	<td>
		<?php echo echo $this->formMonthSelect($form->get('monthyear');?>
	</td>
	<td>
		<?php echo $this->formSelect($form->get('state'));?>
	</td>
	<td>
		<?php $this->formSelect($form->get('city'));?>
	</td>
	<td>
		<?php $this->formSelect($form->get('title'));?>
	</td>
	<td>
		<?php $this->formSelect($form->get('audioname'));?>
	</td>
	<td >
		<?php echo ceil($this->formSelect($form->get('length')) /
		1024).' KB';?>
	</td>
	<td>
		<a href="<?php echo $this->url('audio',  array('action' => 'fetchaudio','id'
			=> $object->file['_id']->__toString()));?>" class="btn btn-default" role="button"> 
			Fetch
		</a>
		<a href="<?php echo $this->url('audio',  array('action' => 'update','id'
			=> $object->file['_id']->__toString()));?>" class="btn btn-success" role="button"> 
			Edit
		</a>
		<a href="<?php echo $this->url('audio',  array('action' => 'splt','id'
			=> $object->file['_id']->__toString()));?>" class="btn btn-info" role="button"> 
			Splt
		</a>
		<a href="<?php echo $this->url('audio',  array('action' => 'delete','id'
			=> $object->file['_id']->__toString()));?>" class="btn btn-warning" role="button"> 
			Delete
		</a>
	</td>
</tr>
<?php
echo $this->formSubmit($form->get('submit')->setValue('Update')); 
echo $this->form()->closeTag(); 
?>