<?php
// module/Album/view/quiz/quiz/add.phtml:
$title = 'Add new quiz';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('quiz', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('url'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();