<?php
// module/Album/view/quiz/quiz/delete.phtml:
$title = 'Delete quiz';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php var_dump($quiz); ?> 
<p>Are you sure that you want to delete
	<?php echo $quiz->getId(); ?>?
</p>
<?php
$url = $this->url('quiz', array(
	'action' => 'delete',
	'id'
	=> $this->id,
	));
	?>
	<form action="<?php echo $url; ?>" method="post">
		<div>
			<input type="hidden" name="id" value="<?php echo (int) $quiz->getId();  ?>" />
			<input type="submit" name="del" value="Yes" />
			<input type="submit" name="del" value="No" />
		</div>
	</form>
