<?php
// module/Album/view/album/album/index.phtml:
$title = 'My Links';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
	<tr>
		<th>Title</th>
		<th>Action</th>
	</tr>
	<?php foreach ($this->links as $key => $link) : // <-- change here! ?>
		<tr>
			<td id="<?php echo $key; ?>"><?php echo $link;?></td>
			<td>
				<a href="<?php echo $link;?>" class = "btn btn-default" role = "button" target="_blank">open</a>
				<a href="<?php echo $this->url('quiz',array('action' => 'fetchcontent', 'id' => $key));?>" class = "btn btn-primary" role = "button">edit</a>
			</td>
		</tr>
	<?php endforeach; ?>
</table>


