<?php
// module/Album/view/link/link/index.phtml:
$title = 'My links';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('quiz', array('action'=>'add'));?>">Add new link</a>
</p>

<table class="table">
	<tr>
		<th>Title</th>
		<th>Web Url</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($this->paginator as $link) : // <-- change here! ?>
	<tr>
		<td><?php echo $this->escapeHtml($link->getTitle());?></td>
		<td><?php echo $this->escapeHtml($link->getUrl());?></td>
		<td>
			<a href="<?php echo $this->url('quiz',
			array('action' => 'edit', 'id' => $link->getId()));?>">Edit</a>
<a href="<?php echo $this->url('quiz',
array('action' => 'delete', 'id' => $link->getId()));?>">Delete</a>
</td>
</tr>
<?php endforeach; ?>
</table>

<?php
echo $this->paginationControl(
// the paginator object
	$this->paginator,
// the scrolling style
	'sliding',
// the partial to use to render the control
	array('partial/paginator.phtml', 'Quiz'),
// the route to link to when a user clicks a control link
	array(
		'route' => 'quiz'
		)
	);
?>