<?php
// module/Album/view/album/album/index.phtml:
$title = 'My Links';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
	<tr>
		<th>Title</th>
		<th>Action</th>
	</tr>
	<?php foreach ($this->links as $key => $link) : // <-- change here! ?>
		<tr>
			<td id="<?php echo $key; ?>"><?php echo $link;?></td>
			<td>
				<a href="" onclick = "delete()">Delete</a>
			</td>
		</tr>
	<?php endforeach; ?>
</table>


<script type="text/javascript">
	$('td').click(function(){
		var cid = $(this).attr('id');
		alert(cid);
		$.ajax({
			url: '/snoopy/deletelink/'+cid,
			success: function() {
				alert('link deleted.');
			}
		});
				// location.reload();
				window.location.replace("http://cet.local/snoopy/displaylinks");
			})
</script>
