<?php
// module/Album/view/album/album/index.phtml:
$title = 'My Blogs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
</p>
<div id="contentarea">
	<div id="innercontentarea">
		<?php if(count($flashMessages)) : ?>
			<ul>
				<?php foreach ($flashMessages as $msg) : ?>
					<li><?php echo $msg; ?></li>
				<?php endforeach; ?>
			</ul>
		<?php endif; ?>
		<table class="table table-striped table-hover table-bordered">
			<thead>
				<tr class="success">
					<th width="*">No</th>
					<th width="*">Date</th>
					<th width="*">State</th>
					<th width="*">City</th>
					<th width="*">Title</th>
					<th width="*">Filename</th>
					<th width="*">Size</th>
					<th width="*">Tag</th>
					<th width="*">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php $i = 1; ?>
				<?php while($object = $objects->getNext()): ?> 
					<tr>
						<td>
							<?php echo 'No.'.$i;?>
						</td>
						<td>
							<?php echo implode("/",$object->file['monthyear']);?>
						</td>
						<td>
							<?php echo $object->file['state'];?>
						</td>
						<td>
							<?php echo $object->file['city'];?>
						</td>
						<td>
							<?php echo $object->file['title'];?>
						</td>
						<td>
							<?php echo $object->file['audioname'];?>
						</td>
						<td >
							<?php echo ceil($object->file['length'] /
							1024).' KB';?>
						</td>
						<td>
							<?php echo $object->file['tag'];?>
						</td>
						<td>
							<a href="<?php echo $this->url('audio',  array('action' => 'fetchaudio','id'
								=> $object->file['_id']->__toString()));?>" class="btn btn-default" role="button"> 
								Fetch
							</a>
							<a href="<?php echo $this->url('audio',  array('action' => 'update','id'
								=> $object->file['_id']->__toString()));?>" class="btn btn-success" role="button"> 
								Edit
							</a>
							<a href="<?php echo $this->url('audio',  array('action' => 'splt','id'
								=> $object->file['_id']->__toString()));?>" class="btn btn-info" role="button"> 
								Splt
							</a>
							<a href="<?php echo $this->url('audio',  array('action' => 'delete','id'
								=> $object->file['_id']->__toString()));?>" class="btn btn-warning" role="button"> 
								Delete
							</a>
						</td>
					</tr>
					<?php $i++ ?>
				<?php endwhile;?>
			</tbody>
		</table>
		<p>
			<a href="<?php echo $this->url('audio',  array('action' => 'upload'));?>"  class="btn btn-default" role="button"> 
				Upload another?
			</a>
		</p>	
		<p>
			<a href="<?php echo $this->url('audio',  array('action' => 'delete','id' => 'all'));?>"  class="btn btn-danger" role="button"> 
				Delete All
			</a>
		</p>
	</div>


</div>

