<?php
// module/Album/view/album/album/index.phtml:
ini_set('display_errors', '1');

$title = 'My Blogs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<body>
	<div class="container">
		<div class="row">
			<div class="span12">
				<center>
					<div class="btn-toolbar">
						<div class="btn-group">
                            <a class="btn btn-primary" onclick="$('#audioLayerControl')[0].copy();"><i class="icon-share icon-white"></i> Copy</a>
                            <a class="btn btn-primary" onclick="$('#audioLayerControl')[0].paste();"><i class="icon-chevron-down icon-white"></i> Paste</a>
                            <a class="btn btn-primary" onclick="$('#audioLayerControl')[0].cut();"><i class="icon-chevron-up icon-white"></i> Cut</a>
                            <a class="btn btn-primary" onclick="$('#audioLayerControl')[0].del();"><i class="icon-remove icon-white"></i> Delete</a>
                        </div>
                        <div class="btn-group">
                         <a class="btn btn-success" onclick="$('#audioLayerControl')[0].selectAll();"><i class="icon-resize-horizontal icon-white"></i> Select All</a>
                         <a class="btn btn-success" onclick="$('#audioLayerControl')[0].zoomIntoSelection();"><i class="icon-plus-sign icon-white"></i> Zoom To Selection</a>
                         <a class="btn btn-success" onclick="$('#audioLayerControl')[0].zoomToFit();"><i class="icon-fullscreen icon-white"></i> Zoom To Fit</a>
                     </div>
                 </div>
             </center>
         </div>
     </div>
     <hr />
     <div class="row">
         <div class="span4">
            <h6>Spectrum</h6>
            <div class="well">
               <div id="spectrum"></div>
           </div>
       </div>
       </div>
       <div class="row">
       <div class="span12">
        <h6>Editor</h6>
        <div class="well">
           <audioLayerControl id="audioLayerControl" title="CloudCompany.mp3" />
       </div>
          <!--<div id="editor">
                <div id="editorbox">
                    <audioLayerControl id="audioLayerControl" title="CloudCompany.mp3" />
                </div>
            </div>-->
        </div>
    </div>
    <hr>
    <div class="row">
    	<div class="span12">
    		<center>
    			<div class="btn-toolbar">
    				<div class="btn-group">
    					<a id="btn_play" class="btn btn-success btn-large" onclick="$('#audioLayerControl')[0].play()" rel="tooltip" title="first tooltip">Play</a>
    					<a id="btn_pause" class="btn btn-success btn-large disabled">Pause</i></a>
    					<a id="btn_stop" class="btn btn-success btn-large" onclick="$('#audioLayerControl')[0].stop()">Stop</a>
    					<a id="btn_loop" class="btn btn-warning btn-large" data-toggle="button" onclick="$('#audioLayerControl')[0].toggleLoop();">Repeat</a>
    				</div>
    				<div class="btn-group">
    					<a class="btn btn-large btn-primary" onclick="$('#audioLayerControl')[0].save($('#savelink')[0]);"><i class="icon-fire"></i> Render</a>
    					<a class="btn btn-large btn-success disabled" id="savelink" download="export.wav"><i class="icon-download"></i> Save</a>
    				</div>
    			</div>
    		</center>
    	</div>
    </div>
    <div class="row">
    	<div class="span4 offset4">
    		<div class="progress progress-striped active">
    			<div id="app-progress" class="bar" style="width: 0%;"></div>
    		</div>
    	</div>
    </div>  
    <br>
    <div class="row">
    	<div class="span1"><br></div>
    	<div class="span2">
    		<h6>Gain</h6>
    		<div class="well" style="height: 130px; position:relative">
    			<p>Change the volume of the selected audio sequence with the given gain multiplicator.</p>

    			<div class="pull-right" style=" position:absolute; bottom: 5px; width: 100%;" >
    				<div class="btn-group" >

    					<button class="btn btn-success" onclick="decrease_db()"><i class="icon-minus"></i></button>
    					<button id="gain-db" class="btn disabled" onclick="gain_btn_clicked()">0 db</button>
    					<button class="btn btn-success" onclick="increase_db()"><i class="icon-plus"></i></button> 
    				</div>
    			</div>
    			<script type="text/javascript">
    				var db_gain = 0;

    				function decrease_db()
    				{
    					--db_gain;
    					update_db_gain_btn();
    				}

    				function increase_db()
    				{
    					++db_gain;
    					update_db_gain_btn();
    				}

    				function update_db_gain_btn()
    				{
    					var gain_btn = $('#gain-db')[0];

    					gain_btn.innerHTML = db_gain + ' db'; 

    					if (db_gain === 0)
    					{
    						gain_btn.className = 'btn disabled';
    					}
    					else
    					{
    						gain_btn.className = 'btn btn-primary';
    					}
    				}

    				function gain_btn_clicked()
    				{
    					$('#audioLayerControl')[0].filterGain(db_gain);
    					db_gain = 0;
    					update_db_gain_btn();
    				}
    			</script>
    		</div>
    	</div>
    	<div class="span2">
    		<h6>Silence</h6>
    		<div class="well" style="height: 130px; position:relative">
    			<p>Silence the selected audio sequence</p>
    			<a style="position:absolute; bottom: 5px; right: 5px"  class="btn btn-primary pull-right" onclick="$('#audioLayerControl')[0].filterSilence();">Apply</a>
    			<br>
    		</div>
    	</div>
     <p class="pull-left"><a href="#">Back to top</a></p>


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <?php echo $this->headScript()
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/ACFIRFilter.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/ACAAFilter.js')) 
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/ACSpectrum.js'))    
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/ACFFT.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/SpectrumWorker.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/SpectrumDisplay.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/audioplayback.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/filedropbox.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/fft.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/audioLayerControl.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/audiosequence.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/AudioSequenceEditor.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/mathutilities.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/wavetrack.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/binarytoolkit.js'))
    ->appendFile($this->basePath('./js/html5-audio-editor/app/js/filesystemutility.js'))
    // ->appendFile($this->basePath('./js/html5-audio-editor/app/js/editorapp.js'))
    ; ?>

    <script type="text/javascript">
    	$(window).load(function()
    	{

    		console.log("Loaded");

    		ACInitFFT();

    		initializeAudioLayerControls();

    		var audioLayerControl = document.querySelector("#audioLayerControl");
    		audioLayerControl.removeAllSequenceEditors();
    		var leftEditor = audioLayerControl.createSequenceEditor("Left Channel");
    		var rightEditor = audioLayerControl.createSequenceEditor("Right Channel");

    		audioLayerControl.setLinkMode(true);
    	});
    </script>
</body>
</html>
