<?php
// module/Mp3/view/mp3/mp3/index.phtml:
$title = 'Split mp3s log';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<?php
	// echo "<pre>";
	// var_dump($this->logArray);
	// echo "</pre>";
	$attribs = array(
		'class' => 'list-inline',
		);

	echo $this->htmlList($this->logArray, true, $attribs);

	?>
</p>
<audio controls>
	<source src="01.mp3" type="audio/mpeg">
		<source src="01.ogg" type="audio/ogg">
			Your browser does not support this audio format.
		</audio>