<?php
$title = 'View Audio Spructrum ';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="form-group">
	<?php 
	$form = $this->form;
		// $form->setAttribute('action', $this->url('ffmpeg', array('action' => 'convert')));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formRow($form->get('mp3'));
	echo $this->formRow($form->get('width'));
	echo $this->formRow($form->get('height'));
	echo $this->formRow($form->get('foreground'));
	echo $this->formRow($form->get('background'));
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();
	?>
</div>
