<?php
// module/Album/view/album/album/index.phtml:
$title = 'Read Questions';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
</p>
<div id="contentarea">
	<div id="innercontentarea">
		<h4>Files Path : <?php echo $this->audioDir; ?></h4>
		<table class="table table-striped table-hover table-bordered">
			<thead>
				<tr class="success">
					<th width="*">No</th>
					<th width="*"> A </th>
					<th width="*"> B </th>
					<th width="*"> C </th>
					<th width="*"> D </th>
					<th width="*">Answer</th>
				</tr>
			</thead>
			<tbody>
				<?php for ($i=0; $i < $num; $i++) {  ?>
					<tr>
					<?php if (array_key_exists($i, $questions)) { ?>
						<td>
							<?php echo $questions[$i]['no'];?>
						</td>
						<td>
							<?php echo $questions[$i]['A'];?>
						</td>
						<td>
							<?php echo $questions[$i]['B'];?>
						</td>
						<td>
							<?php echo $questions[$i]['C'];?>
						</td>
						<td >
							<?php echo $questions[$i]['D'];?>
						</td>
						<td>
							<?php echo $questions[$i]['answer'];?>
						</td>
						<?php }?>
					</tr>
					<tr>
					<?php if (array_key_exists($i, $audioName)) { ?>
						<td>
							<?php echo pathinfo($audioName[$i], PATHINFO_FILENAME); ?>
						</td>
						<td colspan="3">

							<?php 
								echo $this->partial('partial/audio.phtml', array(
									'mp3File' => $audioName[$i].'.mp3',
									'oggFile' => $audioName[$i].'.ogg',
									'id' => $i,
									'class' => 'delete'
									)); 

							?> 
						</td>
						<td colspan="2">
							<button  class="btn btn-primary" onClick="deleteFile('<?php echo pathinfo($audioName[$i], PATHINFO_FILENAME); ?>')")> Delete </button>
							<button  class="btn btn-warning" onClick="mergeup('<?php echo pathinfo($audioName[$i], PATHINFO_FILENAME); ?>')")> Merge Up </button>
						</td>
						<?php } ?>
					</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>


	</div>

	<script type="text/javascript">
		function deleteFile(id){
			$.ajax({
				url: '/tools/deletefile/'+id,
				success: function() {
					alert('File deleted.');
				}
			});
			 location.reload();
		}
		function mergeup(id){
			$.ajax({
				url: '/tools/mergeup/'+id,
				success: function() {
					alert( id + '  File merged with upfile.');
				}
			});
			 
			  setTimeout("location.reload();", 1000);
		}
	</script>