<?php
// module/Album/view/album/album/index.phtml:
$title = 'Read Questions';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
</p>
<div id="contentarea">
	<div id="innercontentarea">
		<table class="table table-striped table-hover table-bordered">
			<thead>
				<tr class="success">
					<th width="*">No</th>
					<th width="*"> A </th>
					<th width="*"> B </th>
					<th width="*"> C </th>
					<th width="*"> D </th>
					<th width="*">Answer</th>
				</tr>
			</thead>
			<tbody>
				<?php $i = 0; ?>
				<?php while($object = $this->objects->getNext()): ?>
					<tr>
						<td>
							<?php echo $object['no'];?>
						</td>
						<td>
							<?php echo $object['A'];?>
						</td>
						<td>
							<?php echo $object['B'];?>
						</td>
						<td>
							<?php echo $object['C'];?>
						</td>
						<td >
							<?php echo $object['D'];?>
						</td>
						<td>
							<?php echo 'answer';?>
						</td>
					</tr>
					<tr>
						<td colspan="6">

							<?php 
							if($i<count($mp3Files)) {

								echo $this->partial('partial/audio.phtml', array(
									'mp3File' => $mp3Files[$object['no']-1],
									'oggFile' => $oggFiles[$object['no']-1],
									// 'mp3File' => $mp3Files[$i],
									// 'oggFile' => $oggFiles[$i],
									)); 
							}
							?> 
						</td>

					</tr>
					<?php $i++; ?>
				<?php endwhile;?>
			</tbody>
		</table>
		<p>
			<a href="<?php echo $this->url('audio',  array('action' => 'upload'));?>"  class="btn btn-default" role="button"> 
				Upload another?
			</a>
		</p>	
		<p>
			<a href="<?php echo $this->url('audio',  array('action' => 'delete','id' => 'all'));?>"  class="btn btn-danger" role="button"> 
				Delete All
			</a>
		</p>
	</div>


</div>

