<?php
// module/Album/view/album/album/index.phtml:
$title = 'Read Questions';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
</p>
<div id="contentarea">
	<div id="innercontentarea">
		<h4>Files Path : <?php echo $this->audioDir; ?></h4>
		<table class="table table-striped table-hover table-bordered">
			<thead>
				<tr class="success">
					<th width="*">No</th>
					<th width="*"> A </th>
					<th width="*"> B </th>
					<th width="*"> C </th>
					<th width="*"> D </th>
					<th width="*">Answer</th>
				</tr>
			</thead>
			<tbody>
				<?php 
				$i = 0; 
				sort($audioName);

				?>
				<?php while($object = $this->objects->getNext()): ?>
					<tr>
						<td>
							<?php echo $object['no'];?>
						</td>
						<td>
							<?php echo $object['A'];?>
						</td>
						<td>
							<?php echo $object['B'];?>
						</td>
						<td>
							<?php echo $object['C'];?>
						</td>
						<td >
							<?php echo $object['D'];?>
						</td>
						<td>
							<?php echo 'answer';?>
						</td>
					</tr>
					<tr>
					<?php if (array_key_exists($object['no']-1, $audioName)) { ?>
						<td>
							<?php echo pathinfo($audioName[$object['no']-1], PATHINFO_FILENAME); ?>
						</td>
						<td colspan="3">

							<?php 
							if($i<count($audioName)) {
								echo $this->partial('partial/audio.phtml', array(
									'mp3File' => $audioName[$object['no']-1].'.mp3',
									'oggFile' => $audioName[$object['no']-1].'.ogg',
									'id' => $i,
									'class' => 'delete'
									)); 

							}
							?> 
						</td>
						<td colspan="2">
							<button  class="btn btn-primary" onClick="deleteFile('<?php echo pathinfo($audioName[$object['no']-1], PATHINFO_FILENAME); ?>')")> Delete </button>
							<button  class="btn btn-warning" onClick="mergeup('<?php echo pathinfo($audioName[$object['no']-1], PATHINFO_FILENAME); ?>')")> Merge Up </button>
						</td>
						<?php } ?>
					</tr>
					<?php 
					$i++; 
					?>
				<?php endwhile;?>
				<?php for($j= $i; $j<count($audioName); $j++) { ?>
				<tr>
					<td>
						<?php echo pathinfo($audioName[$j], PATHINFO_FILENAME); ?>
					</td>
					<td colspan="3">

						<?php 
						
						echo $this->partial('partial/audio.phtml', array(
							'mp3File' => $audioName[$j].'.mp3',
							'oggFile' => $audioName[$j].'.ogg',
									// 'id' => $i,
							'class' => 'delete'
							)); 
							?> 
						</td>
						<td colspan="2">
							<button  class="btn btn-primary" onClick="deleteFile('<?php echo pathinfo($audioName[$j], PATHINFO_FILENAME); ?>')")> Delete </button>
							<button  class="btn btn-warning" onClick="mergeup('<?php echo pathinfo($audioName[$j], PATHINFO_FILENAME); ?>')")> Merge Up </button>
						</td>

					</tr>

					<?php } ?>
				</tbody>
			</table>
		</div>


	</div>

	<script type="text/javascript">
		function deleteFile(id){
			$.ajax({
				url: '/tools/deletefile/'+id,
				success: function() {
					alert('File deleted.');
				}
			});
			 location.reload();
		}
		function mergeup(id){
			$.ajax({
				url: '/tools/mergeup/'+id,
				success: function() {
					alert( id + '  File merged with upfile.');
				}
			});
			 
			  setTimeout("location.reload();", 1000);
		}
	</script>