<?php
// module/Album/view/album/album/index.phtml:
$title = 'Edit Questions';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($this->path); ?></h2>
<p>
</p>
<div id="contentarea">
	<div id="innercontentarea">
		<table id="total" class="table table-striped table-hover table-bordered">
			<thead>
				<tr class="success">
					<th width="*">No</th>
					<!-- <th width="*">Title</th> -->
					<th width="*"> A </th>
					<th width="*"> B </th>
					<th width="*"> C </th>
					<th width="*"> D </th>
					<th width="*">Answer</th>
					<th width="*">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php while($question = $questions->getNext()): ?> 
				<tr id = "tr<?php echo $i ?>" class="trClass">
					<td>
						<?php echo $question['no'] ;?>
					</td>
					<td>
						<?php echo $question['A'];?>
					</td>
					<td>
						<?php echo $question['B'];?>
					</td>
					<td>
						<?php echo $question['C'];?>
					</td>
					<td>
						<?php echo $question['D'];?>
					</td>
					<td>
						<?php echo 'Answer';?>
					</td>
					<td>
						<a href="<?php echo $this->url('tools',  array('action' => 'edit', 'id' => basename($question)));?>" class="btn btn-info" role="button"> 
							Edit
						</a>
					</td>
				</tr>
			<?php endwhile;?>
			</tbody>
		</table>
	</div>

	<h3>The Content in This Doc</h3>
	<?php echo $this->content ; ?>


</div>
