<?php
// module/Album/view/album/album/index.phtml:
$title = 'Edit Questions';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
</p>
<div id="contentarea">
	<div id="innercontentarea">
		<table id="total" class="table table-striped table-hover table-bordered">
			<thead>
				<tr class="success">
					<th width="*">No</th>
					<th width="*">Title</th>
					<th width="*">Path</th>
					<th width="*">Mp3 Number</th>
					<th width="*">Question Number</th>
					<th width="*">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php $i = 1; ?>
				<?php foreach ($objects as $object) { ?> 
				<tr id = "tr<?php echo $i ?>" class="trClass">
					<td>
						<?php echo 'No.'.$i;?>
					</td>
					<td>
						<?php echo basename($object);?>
					</td>
					<td>
						<?php echo $object;?>
					</td>
					<td>
						<a href="<?php echo $this->url('tools',  array('action' => 'scanaudio', 'id' => basename($object)));?>" class="btn btn-info" role="button"> 
							<?php echo count(glob($object.DIRECTORY_SEPARATOR.'*.mp3'));?>
						</a>
					</td>
					<td>
						<a href="<?php echo $this->url('tools',  array('action' => 'scandoc', 'id' => basename($object)));?>" class="btn btn-info" role="button"> 
							<?php echo $this->collection->count(array('quiz' => basename($object)));?> 
						</a>
					</td>
					<td>
						<a href="<?php echo $this->url('tools',  array('action' => 'edit', 'id' => basename($object)));?>" class="btn btn-info" role="button"> 
							Edit
						</a>
					</td>
				</tr>
				<?php $i++ ?>
				<?php };?>
			</tbody>
		</table>
	</div>


</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('#total > tbody  > tr').each(function() {
			// alert($(this).find('td').eq(3).text());
			// alert($(this).find('td').eq(3).find('a').attr('href'));
			if(($(this).find('td').eq(3).text().trim()==0) || ($(this).find('td').eq(4).text().trim()==0)){
				$(this).find('td').eq(3).find('a').attr('class','btn btn-warning');
				$(this).find('td').eq(4).find('a').attr('class','btn btn-warning');
				$(this).find('td').eq(5).find('a').attr('class','btn btn-warning');
			} else if($(this).find('td').eq(3).text().trim()==$(this).find('td').eq(4).text().trim()){
				$(this).find('td').eq(3).find('a').attr('class','btn btn-success');
				$(this).find('td').eq(4).find('a').attr('class','btn btn-success');
				$(this).find('td').eq(5).find('a').attr('class','btn btn-success');
			} 
		});
});


</script>