<?php
// module/Album/view/album/album/index.phtml:
$title = 'Edit Questions';
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($this->path); ?></h2>
<p>
</p>
<div id="contentarea">
	<div id="innercontentarea">
		<table id="total" class="table table-striped table-hover table-bordered">
			<thead>
				<tr class="success">
					<th width="*">No</th>
					<!-- <th width="*">Title</th> -->
					<th width="*"> A </th>
					<th width="*"> B </th>
					<th width="*"> C </th>
					<th width="*"> D </th>
					<th width="*">Answer</th>
					<th width="*">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php while($question = $questions->getNext()): ?> 
				<tr id = "tr<?php echo $i ?>" class="trClass">
					<td>
						<?php echo $question['no'] ;?>
					</td>
					<td>
						<?php echo $question['A'];?>
					</td>
					<td>
						<?php echo $question['B'];?>
					</td>
					<td>
						<?php echo $question['C'];?>
					</td>
					<td>
						<?php echo $question['D'];?>
					</td>
					<td>
						<?php echo 'Answer';?>
					</td>
					<td>
						<a href="<?php echo $this->url('tools',  array('action' => 'edit', 'id' => basename($question)));?>" class="btn btn-info" role="button"> 
							Edit
						</a>
					</td>
				</tr>
			<?php endwhile;?>
			</tbody>
		</table>
	</div>


<?php
// within a view script
$form = $this->form;
$form->prepare();

// Assuming the "contact/process" route exists...
// $form->setAttribute('action', $this->url('tools'));

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>
<div class="form-group col-xs-4">
<?php
    $name = $form->get('begin');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
?></div>

<div class="form-group col-xs-4">
<?php
    $subject = $form->get('end');
    echo $formLabel->openTag() . $subject->getOption('label');
    echo $this->formInput($subject);
    echo $this->formElementErrors($subject);
    echo $formLabel->closeTag();
?></div>
<br />
<div class="form-group col-xs-4">
<?php echo $this->formElement($form->get('submit')) ?>
</div>

<?php echo $this->form()->closeTag() ?>
<br />
<div>

	<h3>The Content in This Doc</h3>
	<?php echo $this->content ; ?>
</div>

</div>
